import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

function safeExec(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
const pkgVersion = pkg.version || '0.0.0'

// Quran_lights pattern: use the package.json version as the displayed version.
// We don't include the git hash or dirty flag in the user-facing version string —
// that information is still captured in APP_BUILD for diagnostic purposes.
const tag = safeExec('git describe --tags --exact-match HEAD')
const shortSha = safeExec('git rev-parse --short HEAD')
const buildTime = new Date().toISOString()

// User-facing version: package.json version (e.g. "1.0.0")
const version = pkgVersion

const info = {
  version,
  pkgVersion,
  commit: shortSha || null,
  tag: tag || null,
  buildTime,
}

const outDir = path.join(root, 'public')
const outFile = path.join(outDir, 'version.json')
writeFileSync(outFile, JSON.stringify(info, null, 2) + '\n', 'utf8')

const srcDir = path.join(root, 'src', 'generated')
mkdirSync(srcDir, { recursive: true })
const srcFile = path.join(srcDir, 'version.ts')
writeFileSync(
  srcFile,
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.\n` +
  `// Regenerated on every build via the "prebuild" script.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)}\n` +
  `export const APP_BUILD = {\n` +
  `  version: ${JSON.stringify(version)},\n` +
  `  pkgVersion: ${JSON.stringify(pkgVersion)},\n` +
  `  commit: ${JSON.stringify(shortSha || null)},\n` +
  `  tag: ${JSON.stringify(tag || null)},\n` +
  `  buildTime: ${JSON.stringify(buildTime)},\n` +
  `}\n`,
  'utf8',
)

console.log(`[version] ${version} (commit=${shortSha || '-'})`)
