import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

function safeExec(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

// Canonical source of truth: public/VERSION (quran_lights pattern).
// Plain "MAJOR.MINOR.PATCH" string, no suffix, no hash, no dirty marker.
// This file is the ONLY thing users see in the footer.
const versionFile = path.join(root, 'public', 'VERSION')
let version = '0.0.0'
if (existsSync(versionFile)) {
  version = readFileSync(versionFile, 'utf8').trim()
}

const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(version)
if (!m) {
  console.error(`[version] public/VERSION is "${version}" — not a clean semver. Fix it.`)
  process.exit(1)
}

// Detect bump type from last commit message (conventional-commits style)
function detectBumpFromLastCommit() {
  const msg = safeExec('git log -1 --pretty=%B')
  if (!msg) return null
  if (/BREAKING CHANGE|!:/m.test(msg)) return 'major'
  if (/^(feat|perf)(\([^)]+\))?!?:/m.test(msg)) return 'minor'
  if (/^(fix|docs|style|refactor|test|build|ci|chore|revert)(\([^)]+\))?!?:/m.test(msg)) return 'patch'
  return null
}

const arg = (process.argv[2] || '').toLowerCase()
let bump = null
if (arg === 'major' || arg === 'minor' || arg === 'patch') bump = arg
else if (arg === 'auto' || arg === '') bump = detectBumpFromLastCommit()
else {
  console.error(`[version] unknown arg "${arg}". Use: auto | major | minor | patch`)
  process.exit(1)
}

if (bump) {
  let [maj, min, pat] = [m[1], m[2], m[3]]
  if (bump === 'major') { maj = String(+maj + 1); min = '0'; pat = '0' }
  else if (bump === 'minor') { min = String(+min + 1); pat = '0' }
  else if (bump === 'patch') { pat = String(+pat + 1) }
  version = `${maj}.${min}.${pat}`

  // Persist to canonical file
  writeFileSync(versionFile, version + '\n', 'utf8')

  // Mirror to package.json
  const pkgPath = path.join(root, 'package.json')
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  pkg.version = version
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8')

  console.log(`[version] bumped to ${version} (${bump})`)
}

// Diagnostics-only (NEVER shown to users)
const shortSha = safeExec('git rev-parse --short HEAD')
const isDirty = safeExec('git status --porcelain') !== ''
const buildTime = new Date().toISOString()

// Generated TS file: user-facing version is CLEAN (quran_lights style).
const srcDir = path.join(root, 'src', 'generated')
mkdirSync(srcDir, { recursive: true })
const srcFile = path.join(srcDir, 'version.ts')
writeFileSync(
  srcFile,
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.\n` +
  `// Regenerated on every build via the "prebuild" script.\n` +
  `// User-facing version is a clean MAJOR.MINOR.PATCH (quran_lights style).\n` +
  `// APP_BUILD is for diagnostics only and is never rendered in the UI.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)}\n` +
  `export const APP_BUILD = {\n` +
  `  version: ${JSON.stringify(version)},\n` +
  `  commit: ${JSON.stringify(shortSha || null)},\n` +
  `  dirty: ${JSON.stringify(isDirty)},\n` +
  `  buildTime: ${JSON.stringify(buildTime)},\n` +
  `}\n`,
  'utf8',
)

// Public JSON for any runtime consumer (download page, etc.)
const outFile = path.join(root, 'public', 'version.json')
writeFileSync(
  outFile,
  JSON.stringify(
    {
      version,
      commit: shortSha || null,
      dirty: isDirty,
      buildTime,
    },
    null,
    2,
  ) + '\n',
  'utf8',
)

console.log(`[version] v${version} (commit=${shortSha || '-'}, dirty=${isDirty})`)
