import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

function safeExec(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
const pkgVersion = pkg.version || '0.0.0'

const tag = safeExec('git describe --tags --abbrev=0')
const commitsSinceTag = tag
  ? Number.parseInt(safeExec(`git rev-list ${tag}..HEAD --count`) || '0', 10)
  : 0
const shortSha = safeExec('git rev-parse --short HEAD')
const dirty = safeExec('git diff --quiet HEAD || echo dirty') === 'dirty'
const buildTime = new Date().toISOString()

let version = pkgVersion
if (tag) {
  const cleanTag = tag.replace(/^v/, '')
  if (commitsSinceTag > 0) {
    version = `${cleanTag}+${commitsSinceTag}.${shortSha || 'local'}`
  } else {
    version = cleanTag
  }
} else if (shortSha) {
  version = `${pkgVersion}-${shortSha}`
}
if (dirty) version += '-dirty'

const info = {
  version,
  pkgVersion,
  commit: shortSha || null,
  tag: tag || null,
  buildTime,
}

const outDir = path.join(root, 'public')
const outFile = path.join(outDir, 'version.json')
writeFileSync(outFile, JSON.stringify(info, null, 2) + '\n', 'utf8')

const srcDir = path.join(root, 'src', 'generated')
mkdirSync(srcDir, { recursive: true })
const srcFile = path.join(srcDir, 'version.ts')
writeFileSync(
  srcFile,
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.\n` +
  `// Regenerated on every build via the "prebuild" script.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)}\n` +
  `export const APP_BUILD = {\n` +
  `  version: ${JSON.stringify(version)},\n` +
  `  pkgVersion: ${JSON.stringify(pkgVersion)},\n` +
  `  commit: ${JSON.stringify(shortSha || null)},\n` +
  `  tag: ${JSON.stringify(tag || null)},\n` +
  `  buildTime: ${JSON.stringify(buildTime)},\n` +
  `}\n`,
  'utf8',
)

console.log(`[version] ${version} (tag=${tag || '-'} commit=${shortSha || '-'} dirty=${dirty})`)
